# scripts/ci/pins.sh — generated by tools/check-versions.py --write-pins
# from versions.json. Do not edit: change versions.json and regenerate.
# shellcheck shell=bash disable=SC2034
PIN_OPENCASCADE_VERSION='8.0.1+p1'
PIN_OPENCASCADE_URL='https://github.com/ayourk/hobbycad-vcpkg/releases/download/sources/opencascade_8.0.1+p1.orig.tar.xz'
PIN_OPENCASCADE_SHA256='966a79fb0fbed4f947b6a3cc456eed61dd584f8a165869afa9f9d232f275172e'
PIN_LIBSLVS_VERSION='3.2.git.20260914+p1'
PIN_LIBSLVS_URL='https://github.com/ayourk/hobbycad-vcpkg/releases/download/sources/libslvs_3.2.git.20260914+p1.orig.tar.gz'
PIN_LIBSLVS_SHA256='c6ccc639b43113733b39d7adaa0d0b05061194fcb0abc22abf758b08a6f42a98'
PIN_LIBWEBP_VERSION='1.6.0'
PIN_LIBWEBP_URL='https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.6.0.tar.gz'
PIN_LIBWEBP_SHA256='e4ab7009bf0629fd11982d4c2aa83964cf244cffba7347ecd39019a9e38c4564'
PIN_NLOHMANN_JSON_VERSION='3.12.0'
PIN_NLOHMANN_JSON_URL='https://github.com/nlohmann/json/archive/refs/tags/v3.12.0.tar.gz'
PIN_NLOHMANN_JSON_SHA256='4b92eb0c06d10683f7447ce9406cb97cd4b453be18d7279320f7b2f025c10187'
