<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================
  translations/sample.ts — HobbyCAD Translation Reference

  File: translations/sample.ts

  This is the reference translation file listing every translatable
  string in HobbyCAD as of Phase 0.  It serves the same purpose as
  themes/sample.qss — a documented starting point.

  To create a new translation:
    1. Copy this file to hobbycad_<locale>.ts (e.g., hobbycad_de.ts)
    2. Edit <translation> elements with translated text
    3. Change type="unfinished" to type="" (or remove the attribute)
    4. Compile with:  lrelease hobbycad_<locale>.ts
    5. The resulting .qm file can be embedded via hobbycad.qrc or
       placed in the translations/ directory for runtime loading

  This file is generated by hand to match the source code.  In normal
  workflow, lupdate generates .ts files automatically:

      lupdate src/ -ts translations/hobbycad_en.ts

  Context names correspond to C++ class names that contain tr() calls.

  SPDX-License-Identifier: GPL-3.0-only
  =================================================================== -->
<!DOCTYPE TS>
<TS version="2.1" language="en_US">

<!-- ===================================================================
  Context: AboutDialog
  File:    src/hobbycad/gui/aboutdialog.cpp
  =================================================================== -->
<context>
    <name>hobbycad::AboutDialog</name>

    <message>
        <source>About HobbyCAD</source>
        <comment>Window title for the About dialog</comment>
        <translation type="unfinished">About HobbyCAD</translation>
    </message>

    <message>
        <source>Open-source parametric 3D CAD for hobbyists.

License: GPL 3.0 (only)
https://github.com/ayourk/HobbyCAD</source>
        <comment>Description text in the About dialog</comment>
        <translation type="unfinished">Open-source parametric 3D CAD for hobbyists.

License: GPL 3.0 (only)
https://github.com/ayourk/HobbyCAD</translation>
    </message>

    <message>
        <source>&lt;b&gt;OpenGL Information:&lt;/b&gt;</source>
        <comment>Section label in the About dialog</comment>
        <translation type="unfinished">&lt;b&gt;OpenGL Information:&lt;/b&gt;</translation>
    </message>

    <message>
        <source>Close</source>
        <comment>Button label to close the About dialog</comment>
        <translation type="unfinished">Close</translation>
    </message>
</context>

<!-- ===================================================================
  Context: CliPanel
  File:    src/hobbycad/gui/clipanel.cpp
  =================================================================== -->
<context>
    <name>hobbycad::CliPanel</name>

    <message>
        <source>Copy</source>
        <comment>Terminal context menu: copy selected text</comment>
        <translation type="unfinished">Copy</translation>
    </message>

    <message>
        <source>Paste</source>
        <comment>Terminal context menu: paste from clipboard</comment>
        <translation type="unfinished">Paste</translation>
    </message>
</context>

<!-- ===================================================================
  Context: MainWindow
  File:    src/hobbycad/gui/mainwindow.cpp
  =================================================================== -->
<context>
    <name>hobbycad::MainWindow</name>

    <!-- ---- File menu ---- -->

    <message>
        <source>&amp;File</source>
        <comment>Menu bar: File menu</comment>
        <translation type="unfinished">&amp;File</translation>
    </message>

    <message>
        <source>&amp;New</source>
        <comment>File menu: create a new document</comment>
        <translation type="unfinished">&amp;New</translation>
    </message>

    <message>
        <source>&amp;Open...</source>
        <comment>File menu: open an existing file</comment>
        <translation type="unfinished">&amp;Open...</translation>
    </message>

    <message>
        <source>&amp;Save</source>
        <comment>File menu: save the current document</comment>
        <translation type="unfinished">&amp;Save</translation>
    </message>

    <message>
        <source>Save &amp;As...</source>
        <comment>File menu: save with a new filename</comment>
        <translation type="unfinished">Save &amp;As...</translation>
    </message>

    <message>
        <source>&amp;Quit</source>
        <comment>File menu: exit the application</comment>
        <translation type="unfinished">&amp;Quit</translation>
    </message>

    <!-- ---- View menu ---- -->

    <message>
        <source>&amp;View</source>
        <comment>Menu bar: View menu</comment>
        <translation type="unfinished">&amp;View</translation>
    </message>

    <message>
        <source>&amp;Terminal</source>
        <comment>View menu: toggle the embedded terminal panel</comment>
        <translation type="unfinished">&amp;Terminal</translation>
    </message>

    <!-- ---- Help menu ---- -->

    <message>
        <source>&amp;Help</source>
        <comment>Menu bar: Help menu</comment>
        <translation type="unfinished">&amp;Help</translation>
    </message>

    <message>
        <source>&amp;About HobbyCAD...</source>
        <comment>Help menu: show the About dialog</comment>
        <translation type="unfinished">&amp;About HobbyCAD...</translation>
    </message>

    <!-- ---- Status bar ---- -->

    <message>
        <source>Ready</source>
        <comment>Status bar: initial ready state</comment>
        <translation type="unfinished">Ready</translation>
    </message>

    <message>
        <source>OpenGL %1.%2 — %3</source>
        <comment>Status bar: OpenGL version and renderer name.
  %1 = major version, %2 = minor version, %3 = renderer string</comment>
        <translation type="unfinished">OpenGL %1.%2 — %3</translation>
    </message>

    <message>
        <source>Reduced Mode — OpenGL 3.3 required</source>
        <comment>Status bar: shown when OpenGL is insufficient</comment>
        <translation type="unfinished">Reduced Mode — OpenGL 3.3 required</translation>
    </message>

    <message>
        <source>The 3D viewport is disabled because OpenGL 3.3+ was not detected. File operations and geometry operations still work normally.</source>
        <comment>Tooltip on the Reduced Mode status bar indicator</comment>
        <translation type="unfinished">The 3D viewport is disabled because OpenGL 3.3+ was not detected. File operations and geometry operations still work normally.</translation>
    </message>

    <!-- ---- Dock panels ---- -->

    <message>
        <source>Feature Tree</source>
        <comment>Dock widget title: the feature/model tree</comment>
        <translation type="unfinished">Feature Tree</translation>
    </message>

    <message>
        <source>Features</source>
        <comment>Header label in the feature tree widget</comment>
        <translation type="unfinished">Features</translation>
    </message>

    <message>
        <source>Terminal</source>
        <comment>Dock widget title: the embedded CLI terminal</comment>
        <translation type="unfinished">Terminal</translation>
    </message>

    <!-- ---- File operations ---- -->

    <message>
        <source>New document created</source>
        <comment>Status bar: after File > New</comment>
        <translation type="unfinished">New document created</translation>
    </message>

    <message>
        <source>Open BREP File</source>
        <comment>File dialog title: opening a file</comment>
        <translation type="unfinished">Open BREP File</translation>
    </message>

    <message>
        <source>BREP Files (*.brep *.brp);;All Files (*)</source>
        <comment>File dialog filter string. Do NOT translate the
  extensions or wildcard patterns — only the labels.</comment>
        <translation type="unfinished">BREP Files (*.brep *.brp);;All Files (*)</translation>
    </message>

    <message>
        <source>Opened: %1</source>
        <comment>Status bar: after successfully opening a file.
  %1 = file path</comment>
        <translation type="unfinished">Opened: %1</translation>
    </message>

    <message>
        <source>Open Failed</source>
        <comment>Error dialog title: file open failure</comment>
        <translation type="unfinished">Open Failed</translation>
    </message>

    <message>
        <source>Could not open file:
%1</source>
        <comment>Error dialog body: file open failure.
  %1 = file path</comment>
        <translation type="unfinished">Could not open file:
%1</translation>
    </message>

    <message>
        <source>Save BREP File</source>
        <comment>File dialog title: saving a file</comment>
        <translation type="unfinished">Save BREP File</translation>
    </message>

    <message>
        <source>Saved: %1</source>
        <comment>Status bar: after successfully saving a file.
  %1 = file path</comment>
        <translation type="unfinished">Saved: %1</translation>
    </message>

    <message>
        <source>Save Failed</source>
        <comment>Error dialog title: file save failure</comment>
        <translation type="unfinished">Save Failed</translation>
    </message>

    <message>
        <source>Could not save file:
%1</source>
        <comment>Error dialog body: file save failure.
  %1 = file path</comment>
        <translation type="unfinished">Could not save file:
%1</translation>
    </message>

    <!-- ---- Unsaved changes dialog ---- -->

    <message>
        <source>Unsaved Changes</source>
        <comment>Dialog title: document has unsaved modifications</comment>
        <translation type="unfinished">Unsaved Changes</translation>
    </message>

    <message>
        <source>The document has been modified.</source>
        <comment>Dialog text: informing user of unsaved changes</comment>
        <translation type="unfinished">The document has been modified.</translation>
    </message>

    <message>
        <source>Do you want to save your changes?</source>
        <comment>Dialog informative text: asking what to do</comment>
        <translation type="unfinished">Do you want to save your changes?</translation>
    </message>

    <message>
        <source>Close Without Saving</source>
        <comment>Button: discard changes and close</comment>
        <translation type="unfinished">Close Without Saving</translation>
    </message>

    <message>
        <source>Save and Close</source>
        <comment>Button: save the document then close</comment>
        <translation type="unfinished">Save and Close</translation>
    </message>

    <message>
        <source>Cancel</source>
        <comment>Button: cancel the close operation</comment>
        <translation type="unfinished">Cancel</translation>
    </message>
</context>

<!-- ===================================================================
  Context: DiagnosticDialog
  File:    src/hobbycad/gui/reduced/diagnosticdialog.cpp
  =================================================================== -->
<context>
    <name>hobbycad::DiagnosticDialog</name>

    <message>
        <source>OpenGL Diagnostic — Reduced Mode</source>
        <comment>Window title for the GPU diagnostic dialog</comment>
        <translation type="unfinished">OpenGL Diagnostic — Reduced Mode</translation>
    </message>

    <message>
        <source>&lt;b&gt;OpenGL 3.3 or higher is required for the 3D viewport but was not detected.&lt;/b&gt;&lt;br&gt;&lt;br&gt;HobbyCAD is running in Reduced Mode. File operations, geometry tools, and scripting work normally, but the 3D viewport is disabled.</source>
        <comment>Explanation shown at the top of the diagnostic dialog</comment>
        <translation type="unfinished">&lt;b&gt;OpenGL 3.3 or higher is required for the 3D viewport but was not detected.&lt;/b&gt;&lt;br&gt;&lt;br&gt;HobbyCAD is running in Reduced Mode. File operations, geometry tools, and scripting work normally, but the 3D viewport is disabled.</translation>
    </message>

    <message>
        <source>&lt;b&gt;Detected Graphics Information:&lt;/b&gt;</source>
        <comment>Section label above the GPU info text</comment>
        <translation type="unfinished">&lt;b&gt;Detected Graphics Information:&lt;/b&gt;</translation>
    </message>

    <message>
        <source>Copy to Clipboard</source>
        <comment>Button: copy GPU diagnostic info to clipboard</comment>
        <translation type="unfinished">Copy to Clipboard</translation>
    </message>

    <message>
        <source>Copied!</source>
        <comment>Button text after clipboard copy succeeds</comment>
        <translation type="unfinished">Copied!</translation>
    </message>

    <message>
        <source>GPU Upgrade Guidance:</source>
        <comment>Section label for vendor-specific upgrade advice</comment>
        <translation type="unfinished">GPU Upgrade Guidance:</translation>
    </message>

    <message>
        <source>NVIDIA GPU detected. OpenGL 3.3 is supported by GeForce 8 series and newer. Update drivers via nvidia-driver-XXX packages or the NVIDIA website.</source>
        <comment>Vendor-specific guidance for NVIDIA GPUs</comment>
        <translation type="unfinished">NVIDIA GPU detected. OpenGL 3.3 is supported by GeForce 8 series and newer. Update drivers via nvidia-driver-XXX packages or the NVIDIA website.</translation>
    </message>

    <message>
        <source>AMD GPU detected. OpenGL 3.3 is supported by Radeon HD 5000 series and newer. The open-source Mesa radeonsi driver (Ubuntu default) provides OpenGL 4.6.</source>
        <comment>Vendor-specific guidance for AMD GPUs</comment>
        <translation type="unfinished">AMD GPU detected. OpenGL 3.3 is supported by Radeon HD 5000 series and newer. The open-source Mesa radeonsi driver (Ubuntu default) provides OpenGL 4.6.</translation>
    </message>

    <message>
        <source>Intel GPU detected. OpenGL 3.3 is supported by HD Graphics 2500 (Ivy Bridge) and newer. The open-source Mesa i965/iris driver (Ubuntu default) provides OpenGL 4.6.</source>
        <comment>Vendor-specific guidance for Intel GPUs</comment>
        <translation type="unfinished">Intel GPU detected. OpenGL 3.3 is supported by HD Graphics 2500 (Ivy Bridge) and newer. The open-source Mesa i965/iris driver (Ubuntu default) provides OpenGL 4.6.</translation>
    </message>

    <message>
        <source>GPU vendor not recognized. OpenGL 3.3 requires a GPU from approximately 2008 or newer with up-to-date drivers.</source>
        <comment>Generic guidance when GPU vendor is unknown</comment>
        <translation type="unfinished">GPU vendor not recognized. OpenGL 3.3 requires a GPU from approximately 2008 or newer with up-to-date drivers.</translation>
    </message>

    <message>
        <source>&lt;i&gt;Tip: Check that your GPU drivers are up to date. On Ubuntu, use &apos;Additional Drivers&apos; in Software &amp; Updates, or install Mesa updates via apt.&lt;/i&gt;</source>
        <comment>General driver update tip</comment>
        <translation type="unfinished">&lt;i&gt;Tip: Check that your GPU drivers are up to date. On Ubuntu, use &apos;Additional Drivers&apos; in Software &amp; Updates, or install Mesa updates via apt.&lt;/i&gt;</translation>
    </message>

    <message>
        <source>Don&apos;t show this again</source>
        <comment>Checkbox: suppress the diagnostic dialog</comment>
        <translation type="unfinished">Don&apos;t show this again</translation>
    </message>

    <message>
        <source>Continue in Reduced Mode</source>
        <comment>Button: dismiss the dialog and continue</comment>
        <translation type="unfinished">Continue in Reduced Mode</translation>
    </message>

    <message>
        <source>Exit</source>
        <comment>Button: close the application</comment>
        <translation type="unfinished">Exit</translation>
    </message>
</context>

<!-- ===================================================================
  Context: ReducedViewport
  File:    src/hobbycad/gui/reduced/reducedviewport.cpp
  =================================================================== -->
<context>
    <name>hobbycad::ReducedViewport</name>

    <message>
        <source>3D viewport disabled

OpenGL 3.3 required
Click for details</source>
        <comment>Placeholder text painted on the disabled viewport.
  Shown centered on a dark background.</comment>
        <translation type="unfinished">3D viewport disabled

OpenGL 3.3 required
Click for details</translation>
    </message>
</context>

<!-- ===================================================================
  Context: QObject (global — used in main.cpp)
  File:    src/hobbycad/main.cpp
  =================================================================== -->
<context>
    <n>QObject</n>

    <message>
        <source>Theme Rejected</source>
        <comment>Warning dialog title: theme failed validation</comment>
        <translation type="unfinished">Theme Rejected</translation>
    </message>

    <message>
        <source>The theme "%1" was not applied because it contains rules where the background color equals the text color, which would make text invisible.

%2</source>
        <comment>Warning dialog body: theme validation failure.
  %1 = theme file path, %2 = detailed warnings</comment>
        <translation type="unfinished">The theme "%1" was not applied because it contains rules where the background color equals the text color, which would make text invisible.

%2</translation>
    </message>
</context>

</TS>

