#!/usr/bin/env python3
# =====================================================================
#  tools/check-versions.py — dependency version parity across channels
#  SPDX-License-Identifier: GPL-3.0-only
#  Part of HobbyCAD (ayourk/hobbycad)
# =====================================================================
#
#  Reads versions.json at the repository root and checks that every place
#  a dependency version is written agrees with it:
#
#    vcpkg.json overrides                 (Windows and macOS static builds)
#    ../HobbyCAD-vcpkg/versions/baseline  (the registry, when checked out)
#    ../HobbyCAD-homebrew/Formula         (the tap, when checked out)
#    packaging/flatpak manifest           (module source tarballs, runtime)
#    .github/workflows/*.yml              (release tarballs the jobs fetch,
#                                          distribution packages used instead)
#    tools/macos/*.sh                     (Homebrew keg pins)
#    scripts/ci/pins.sh                   (source URLs and checksums the CI
#                                          build scripts use; generated)
#    packaging/rpm, packaging/arch        (build dependencies)
#
#  --write-pins regenerates scripts/ci/pins.sh from versions.json.
#
#  One line per finding; exit status 1 when anything drifts, so it can gate
#  a commit or run in CI. Sibling repositories that are not checked out are
#  reported as skipped, not as drift. Run from anywhere; -v lists agreements.
# =====================================================================
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V = json.load(open(ROOT / "versions.json"))
DEPS = V["dependencies"]
findings, notes = [], []


def drift(where, what):
    findings.append(f"{where}: {what}")


def ok(where, what):
    notes.append(f"{where}: {what}")


def judge(where, good, what, expected):
    (ok if good else drift)(where, what if good else f"{what}; expected {expected}")


EXPECTED_TARBALLS = {d["tarball"]: k for k, d in DEPS.items() if "tarball" in d}
SOURCES = {k: d["source"] for k, d in DEPS.items() if "source" in d}


# ---- scripts/ci/pins.sh (generated) ----------------------------------------
PINS = ROOT / "scripts" / "ci" / "pins.sh"


def render_pins():
    out = ["# scripts/ci/pins.sh — generated by tools/check-versions.py --write-pins",
           "# from versions.json. Do not edit: change versions.json and regenerate.",
           "# shellcheck shell=bash disable=SC2034"]
    for name, src in SOURCES.items():
        d = DEPS[name]
        key = re.sub(r"[^A-Z0-9]", "_", name.upper())
        ver = d["version"] + (f"+{d['patch']}" if d.get("patch") else "")
        out += [f"PIN_{key}_VERSION='{ver}'", f"PIN_{key}_URL='{src['url']}'", f"PIN_{key}_SHA256='{src['sha256']}'"]
    return "\n".join(out) + "\n"


if "--write-pins" in sys.argv:
    PINS.parent.mkdir(parents=True, exist_ok=True)
    PINS.write_text(render_pins())
    print(f"wrote {PINS.relative_to(ROOT)}")
judge("scripts/ci/pins.sh", PINS.exists() and PINS.read_text() == render_pins(),
      "pins match versions.json", "regenerated pins (tools/check-versions.py --write-pins)")
for name, src in SOURCES.items():
    judge("versions.json", bool(re.fullmatch(r"[0-9a-f]{64}", src["sha256"])), f"{name} source sha256", "64 hex digits")
FAMILY = {"opencascade": "opencascade", "libslvs": "libslvs", "lib3mf": "lib3mf",
          "libopenmesh": "openmesh", "meshfix": "meshfix"}


def check_release_tarballs(where, text):
    """Every release-asset orig tarball named in text must be one of ours."""
    for name in sorted(set(re.findall(r"releases/download/sources/([A-Za-z0-9_.+~-]+\.orig\.tar\.(?:gz|xz))", text))):
        if name in EXPECTED_TARBALLS:
            ok(where, name)
        else:
            fam = FAMILY.get(name.split("_", 1)[0], "?")
            drift(where, f"fetches {name}; expected {DEPS.get(fam, {}).get('tarball', '?')}")


# ---- vcpkg.json overrides ------------------------------------------------
vj = json.load(open(ROOT / "vcpkg.json"))
for o in vj.get("overrides", []):
    name = o["name"]
    ver = o.get("version") or o.get("version-string") or o.get("version-semver")
    key = {"qtbase": "qt", "qtsvg": "qt", "qttools": "qt"}.get(name, name)
    if key in DEPS:
        want = DEPS[key].get("vcpkg", DEPS[key]["version"])
        judge("vcpkg.json", ver == want, f"override {name} {ver}", want)
        # A new cut that keeps the version string moves the port-version
        # instead; an override left behind would pin the previous tarball.
        if "vcpkg_port_version" in DEPS[key]:
            pv = o.get("port-version", 0)
            judge("vcpkg.json", pv == DEPS[key]["vcpkg_port_version"], f"override {name} port-version {pv}", DEPS[key]["vcpkg_port_version"])

# ---- registry baseline (sibling checkout) --------------------------------
reg = ROOT.parent / "HobbyCAD-vcpkg" / "versions" / "baseline.json"
if reg.exists():
    base = json.load(open(reg))["default"]
    for port, key in (("opencascade", "opencascade"), ("libslvs", "libslvs"), ("lib3mf", "lib3mf"), ("openmesh", "openmesh"),
                      ("meshfix", "meshfix"), ("libgit2", "libgit2"), ("qtbase", "qt"), ("qtsvg", "qt"), ("qttools", "qt")):
        if port in base:
            got = base[port]["baseline"]
            want = DEPS[key].get("vcpkg", DEPS[key]["version"])
            judge("registry", got == want, f"{port} {got}", want)
            if port == key and "vcpkg_port_version" in DEPS[key]:
                pv = base[port].get("port-version", 0)
                judge("registry", pv == DEPS[key]["vcpkg_port_version"], f"{port} port-version {pv}", DEPS[key]["vcpkg_port_version"])
else:
    notes.append("registry: ../HobbyCAD-vcpkg not checked out, skipped")

# ---- Homebrew tap (sibling checkout) -------------------------------------
tap = ROOT.parent / "HobbyCAD-homebrew" / "Formula"
if tap.exists():
    allowed = set(V.get("brew_versioned_formulas_allowed", []))
    for f in sorted(tap.glob("*.rb")):
        name, text = f.stem, f.read_text()
        if "@" in name and name not in allowed:
            drift("tap", f"stale versioned formula {name}.rb")
            continue
        m = re.search(r'url\s+"([^"]+)"', text)
        url = m.group(1) if m else ""
        base = url.rsplit("/", 1)[-1]
        if base in EXPECTED_TARBALLS:
            ok("tap", f"{name} <- {base}")
            dep = EXPECTED_TARBALLS[base]
            m = re.search(r'sha256\s+"([0-9a-f]{64})"', text)
            if dep in SOURCES and m:
                judge("tap", m.group(1) == SOURCES[dep]["sha256"], f"{name} sha256", SOURCES[dep]["sha256"])
        elif name.startswith("libgit2@"):
            want = DEPS["libgit2"]["version"]
            judge("tap", f"v{want}.tar.gz" in url, f"{name} <- {base}", f"libgit2 {want}")
        elif name.startswith("libzip@"):
            want = DEPS["libzip"]["version"]
            judge("tap", want in url, f"{name} <- {base}", f"libzip {want}")
        elif base.split("_", 1)[0] in FAMILY:
            fam = FAMILY[base.split("_", 1)[0]]
            drift("tap", f"{name} fetches {base}; expected {DEPS[fam]['tarball']}")
else:
    notes.append("tap: ../HobbyCAD-homebrew not checked out, skipped")

# ---- Flatpak manifest ----------------------------------------------------
fp = ROOT / "packaging" / "flatpak" / "org.hobbycad.HobbyCAD.yml"
if fp.exists():
    text = fp.read_text()
    check_release_tarballs("flatpak", text)
    for name, src in SOURCES.items():
        m = re.search(re.escape(src["url"]) + r"\s*\n\s*sha256:\s*([0-9a-f]{64})", text)
        if m:
            judge("flatpak", m.group(1) == src["sha256"], f"{name} sha256", src["sha256"])
    for dep, pat in (("nlohmann-json", r"nlohmann/json/archive/refs/tags/v([0-9.]+)\.tar\.gz"),
                     ("libgit2", r"libgit2/archive/refs/tags/v([0-9.]+)\.tar\.gz"),
                     ("libwebp", r"libwebp-([0-9.]+)\.tar\.gz")):
        m = re.search(pat, text)
        if m:
            judge("flatpak", m.group(1) == DEPS[dep]["version"], f"{dep} {m.group(1)}", DEPS[dep]["version"])
    m = re.search(r"^runtime:\s*(\S+)\s*\nruntime-version:\s*'?([0-9.]+)", text, re.M)
    if m and m.group(1) == "org.kde.Platform":
        drift("flatpak", f"Qt comes from {m.group(1)} {m.group(2)}; expected Qt {DEPS['qt']['version']} built in the manifest")

# ---- workflows -----------------------------------------------------------
# Distribution packages that stand in for a pinned dependency in a job that
# installs its own build dependencies (RPM, Arch). Each is drift until the
# job builds the pinned version from source.
DISTRO = {"opencascade-devel": "opencascade", "opencascade": "opencascade", "lib3mf-devel": "lib3mf", "lib3mf": "lib3mf",
          "libgit2-devel": "libgit2", "libgit2": "libgit2", "json-devel": "nlohmann-json", "nlohmann-json": "nlohmann-json",
          "qt6-qtbase-devel": "qt", "qt6-base": "qt", "libzip-devel": "libzip", "libzip": "libzip",
          "libwebp-devel": "libwebp", "libwebp": "libwebp"}
RUNTIME = {k for k, d in DEPS.items() if d.get("scope", "runtime") == "runtime"}


def scan_distro_packages(where, text):
    installing = False
    seen = set()
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("#"):
            continue
        if re.match(r"(dnf install|pacman -S|depends=\(|makedepends=\(|BuildRequires:)", s):
            installing = True
        if installing:
            for tok in re.findall(r"[A-Za-z0-9_+.-]+", s):
                if tok in DISTRO and DISTRO[tok] in RUNTIME and DISTRO[tok] not in seen:
                    seen.add(DISTRO[tok])
                    drift(where, f"{DISTRO[tok]} comes from the distribution ({tok}); expected {DEPS[DISTRO[tok]]['version']} built from source")
            if s.startswith("BuildRequires:") or not (s.endswith("\\") or s.endswith("(") or s.startswith("'")):
                installing = s.startswith("'") or s.endswith("(")


for pf in (ROOT / "packaging" / "rpm" / "hobbycad.spec", ROOT / "packaging" / "arch" / "PKGBUILD"):
    if pf.exists():
        scan_distro_packages(str(pf.relative_to(ROOT)), pf.read_text())
for wf in sorted((ROOT / ".github" / "workflows").glob("*.yml")):
    text = wf.read_text()
    where = f"workflow {wf.name}"
    check_release_tarballs(where, text)
    for dep, pat in (("nlohmann-json", r"nlohmann/json/archive/refs/tags/v([0-9.]+)\.tar\.gz"), ("libwebp", r"libwebp-([0-9.]+)\.tar\.gz")):
        for ver in sorted(set(re.findall(pat, text))):
            judge(where, ver == DEPS[dep]["version"], f"{dep} {ver}", DEPS[dep]["version"])
    # A pinned source fetched by hand bypasses the checksum and the pin.
    for name, src in SOURCES.items():
        if src["url"] in text:
            drift(where, f"downloads {name} directly; use scripts/ci/fetch.sh or its build script")
    if wf.name in ("linux-rpm.yml", "linux-arch.yml"):
        scan_distro_packages(where, text)

# ---- macOS scripts -------------------------------------------------------
for sh in sorted((ROOT / "tools" / "macos").glob("*.sh")):
    text = sh.read_text()
    for dep, ver in sorted(set(re.findall(r"(opencascade|libgit2|libzip|lib3mf|libslvs)@([0-9][0-9.]*)", text))):
        judge(f"tools/macos/{sh.name}", ver == DEPS[dep]["version"], f"{dep}@{ver}", DEPS[dep]["version"])

# ---- report --------------------------------------------------------------
if "-v" in sys.argv:
    for n in notes:
        print("  ok   ", n)
for f in findings:
    print("  DRIFT", f)
print(f"check-versions: {len(findings)} drift(s), {len(notes)} agreement(s)")
sys.exit(1 if findings else 0)
